3-е занятие
js-tasks-ru/js-20200928_azorinmsu pull request #3
Opened 2020-10-07 22:35 UTC by azorinmsu

2020-10-07 22:42 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
createGetter
+ should return existed properties
+ should return "undefined" for properties which does not exist
+ gets obj.property
+ returns undefined for no property
+ gets obj.nested.property
+ returns undefined for no nested.property
+ gets more.nested.property
```
```diff
trimSymbols
+ should remove an identical consecutive characters that exceed the specified size
+ should return empty string if it was passed to function like an argument
+ should return empty string if "size" equal 0
+ should return the same string if "size" parameter wasn't specified
```
```diff
invertObj
+ should swap keys and values and return new object
+ should return empty object if was passed object without values
+ should return "undefined" if object wasn't passed
```
```diff
uniq
+ should return array with uniq values
+ should return empty array if was passed array without values
+ should return empty array if arguments wasn't passed
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-10-09 19:17 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    const properties = path.split(".");
было бы неплохо вынести `path.split('.')` в родительскую функцию, иначе данная операция будет выполняться каждый раз при вызове геттера, хотя данное значение требуется рассчитать только один раз при создании геттера

2020-10-09 19:18 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +        return undefined;
мы не возращаем и не присваиваем `undefined` явным образом, будет достаточно просто выполнить `return`

2020-10-09 19:20 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    let entries = new Map(Object.entries(obj));
В данном случае `new Map` не несет никакой функциональной нагрузки. Все что нужно сделать внутри цикла - проверить есть ли данное свойство у объекта, а для проверки наличия свойства у объекта операции `new Map(Object.entries(obj))` не нужны

2020-10-09 19:20 UTC, dosandk requested changes
необходимо поправить решение `createGetter`

2020-10-24 21:40 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
- should be rendered correctly
- should not have default sorting
- should sort "asc" correctly for "sortType" equal string
- should sort "desc" correctly for "sortType" equal string
- should sort "asc" correctly for "sortType" equal number
- should sort "desc" correctly for "sortType" equal number
- should have ability to be destroyed
```
```diff
SortableTable v2 компонент без динамической загрузки данных
- should be rendered correctly
- should have default sorting marked by arrow icon
- should sort "desc" correctly for "sortType" equal string
- should sort "desc" correctly for "sortType" equal number
- should move arrow icon to the corresponding column after sorting
- should have ability to be destroyed
```
```diff
ColumnChart компонент
- should be rendered correctly
- should have ability to define label
- should have ability to define link
- should have ability to define total value
- should have property 'chartHeight
- should render data correctly
- should have ability to be updated by new "data" values (should re-render only body with charts columns)
- should have loading indication if data wasn't passed 
- should have ability to be removed
```
```diff
NotificationMessage компонент
- should be rendered correctly
- should have ability to set duration
- should be removed after time defined in duration property
- should have ability to set message
- should have ability to set 'success' type of message
- should have ability to set 'error' type of message
- should have ability to define target element for rendering
- should have ability to be destroyed
```
```diff
Tooltip компонент
- should be rendered correctly
- should be shown when moving over the element with data-tooltip attribute
- should be hidden when moving out from the element with data-tooltip attribute
- should have ability to be destroyed
```
```diff
createGetter
+ should return existed properties
+ should return "undefined" for properties which does not exist
+ gets obj.property
+ returns undefined for no property
+ gets obj.nested.property
+ returns undefined for no nested.property
+ gets more.nested.property
```
```diff
trimSymbols
+ should remove an identical consecutive characters that exceed the specified size
+ should return empty string if it was passed to function like an argument
+ should return empty string if "size" equal 0
+ should return the same string if "size" parameter wasn't specified
```
```diff
invertObj
+ should swap keys and values and return new object
+ should return empty object if was passed object without values
+ should return "undefined" if object wasn't passed
```
```diff
uniq
+ should return array with uniq values
+ should return empty array if was passed array without values
+ should return empty array if arguments wasn't passed
```

2023-11-24 09:51 UTC, closed without merging